# Generated by Django 5.1.6 on 2025-04-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENurseryApp', '0002_product'),
    ]

    operations = [
    ]
