# Generated by Django 5.1.6 on 2025-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENurseryApp', '0003_auto_20250402_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categpry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
